var person = new Object();
person.firstname='Kamal';
person.middlename="Singh";
person.lastname="Sandhu";
person.age=34;
person.email="Sohrab@abc.ca";
document.write(person+"<br><br>");
document.write(person.firstname+"<br><br>");
document.write(person.email+"");
console.log(person);
console.log(person.lastname);
